//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DrewOlsonAssignment3
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class AdvisingDatabaseEntities1 : DbContext
    {
        public AdvisingDatabaseEntities1()
            : base("name=AdvisingDatabaseEntities1")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public DbSet<AdvisorTable> AdvisorTables { get; set; }
        public DbSet<AppointmentTable> AppointmentTables { get; set; }
        public DbSet<StudentTable> StudentTables { get; set; }
        public DbSet<UserTable> UserTables { get; set; }
    }
}
