//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DrewOlsonAssignment3
{
    using System;
    using System.Collections.Generic;
    
    public partial class AdvisorTable
    {
        public int Id { get; set; }
        public string AdvisorFirstName { get; set; }
        public string AdvisorLastName { get; set; }
        public string AdvisorUserName { get; set; }
        public string AdvisorOfficeLocation { get; set; }
    }
}
