//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DrewOlsonAssignment3
{
    using System;
    using System.Collections.Generic;
    
    public partial class AppointmentTable
    {
        public int AppointmentID { get; set; }
        public string AppointmentTime { get; set; }
        public string AppointmentDate { get; set; }
        public string AppointmentReason { get; set; }
        public string AdvisorUserName { get; set; }
        public string StudentUserName { get; set; }
    }
}
