//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DrewOlsonAssignment3
{
    using System;
    using System.Collections.Generic;
    
    public partial class StudentTable
    {
        public int StudentID { get; set; }
        public string StudentFirstName { get; set; }
        public string StudentLastName { get; set; }
        public string StudentUserName { get; set; }
        public string StudentAdvisorUserName { get; set; }
        public string StudentMajor { get; set; }
    }
}
